# This file was generated by GoReleaser. DO NOT EDIT.
cask "slis" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "72c926fe76f9ac0050a0ec37cfe027cbfd572f2eac7cb2fc9aa8b3b76621ceef"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "37ba9c972b1b9277792c4991bbb641226d5ba2bc265a62eceff1b2ae6c91fac4"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24255f520923bd707d592ba664c1ae52ff725e7a89da33e227326d2ecb342a22"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "080d281d1243140155c512e7f81ee8d369ff3bf6287777e68abb39dbe2701e10"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slis"
  desc "Multi-repo worktree cockpit: a TUI + CLI for working across many git repos at once"
  homepage "https://github.com/jonnyom/slis"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "terminal-notifier",
    ]

  binary "slis"
  binary "slis-ui"
  binary "zmx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slis"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slis-ui"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zmx"]
    end
  end

  # No zap stanza required

end
