# This file was generated by GoReleaser. DO NOT EDIT.
cask "slis" do
  version "0.14.4"

  on_macos do
    on_arm do
      sha256 "a85e2dc01a4d55a1637faf4754480b3e7d707eadd8cd9aad958daed09c28f933"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1c8057317a0523650f31f5d8871431cc20af8b434c8ceaca12ad72c9d4d4861"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6d65bbc3759333a27fcd6edd71d01abf9c4a368178826f5a761c627e8dc7f570"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee8db91ed69def9bd73e4bca0037bdc6e8d04a0d9fa302666ded60533aca97ae"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_linux_amd64.tar.gz"
    end
  end

  name "slis"
  desc "Multi-repo worktree cockpit: a TUI + CLI for working across many git repos at once"
  homepage "https://github.com/jonnyom/slis"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "terminal-notifier",
    ]

  binary "slis"
  binary "slis-ui"
  binary "zmx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slis"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slis-ui"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zmx"]
    end
  end

  # No zap stanza required
end
