# This file was generated by GoReleaser. DO NOT EDIT.
cask "slis" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "37a4f2ca4e14bc113e3044a0a28653f5ab5a6495127488efd57b0f36520fc508"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b06d8f0e99ea44c080308ac8870eef1d10151bf1c274dbbeea5cb83ea0b69fe"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b231e1e473be2037cce1eff659a39cf8b780e57aeee5b5e307a42c0ea5a0c12f"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6478f77e54cd4864a50b499d331b2f3f84956bb53ed78b9f0b03edc18fc39f9"
      url "https://github.com/jonnyom/slis/releases/download/v#{version}/slis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slis"
  desc "Multi-repo worktree cockpit: a TUI + CLI for working across many git repos at once"
  homepage "https://github.com/jonnyom/slis"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "terminal-notifier",
    ]

  binary "slis"
  binary "slis-ui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slis"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slis-ui"]
    end
  end

  # No zap stanza required

end
